spring:
  application:
    name: msFavorito
  datasource:
    url: jdbc:mariadb://localhost:3305/bdtest
    username: root
    password: lampi
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: false


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: will-group
      auto-offset-reset: latest # Define o ponto de início da leitura de mensagens
      enable-auto-commit: true # Se o consumidor deve confirmar automaticamente as mensagens
      auto-commit-interval: 1000 # Intervalo em milissegundos para o commit automático
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic:
        name: Microservice_Favorito
      
file: upload-dir:/home/runner/work/lojaonline/UploadDir
jwt:
  secret: ' senhachavesenha '
