spring:
  datasource:
    url: jdbc:mariadb://localhost:3305/bdtest
    username: root
    password: lampi
    driver-class-name: org.mariadb.jdbc.Driver
    
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: will-group
      auto-offset-reset: latest # Define o ponto de início da leitura de mensagens
      enable-auto-commit: true # Se o consumidor deve confirmar automaticamente as mensagens
      auto-commit-interval: 1000 # Intervalo em milissegundos para o commit automático
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic:
        name: Microservice_Carrinho


file: upload-dir:/home/runner/work/lojaonline/UploadDir
jwt:
  secret: senhachavesenha
